In [8]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy as sp
import math
import matplotlib.pyplot as plt
from scipy import signal
import os
setting = pd.read_csv('setting_motion.csv', header = 0, usecols = [0,1])
MOTION = setting.iloc[0,1] #The motion capture data
Label = pd.read_csv(MOTION, header=2, nrows = 1)
Markers = pd.read_csv(MOTION, header=5, )
time = pd.read_csv(MOTION, header=6, usecols = [1])

num_frames = len(Markers.iloc[:,0])
num_markers = 31
Markers.describe()

,Frame,Time (Seconds),X,Y,Z,X.1,Y.1,Z.1,X.2,Y.2,...,Z.27,X.28,Y.28,Z.28,X.29,Y.29,Z.29,X.30,Y.30,Z.30
count,30272.000000,30272.00000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,...,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000,30272.000000
mean,15135.500000,151.35500,0.359491,0.801746,0.373742,0.335609,1.145735,0.243114,0.305931,0.041187,...,0.212379,0.488663,0.995636,0.227427,0.515282,1.404905,0.197206,0.483655,0.784444,0.562016
std,8738.918011,87.38918,0.108502,0.142000,0.173089,0.107127,0.230222,0.207891,0.121214,0.014335,...,0.034458,0.114990,0.213469,0.164848,0.125916,0.263793,0.266684,0.148753,0.169198,0.165892
min,0.000000,0.00000,-0.636953,0.406149,0.102509,-0.626547,0.644285,-0.045137,-0.754689,0.032543,...,0.133649,-0.516029,0.588686,0.058115,-0.669319,0.755607,-0.253200,-0.832971,0.347818,0.213158
25%,7567.750000,75.67750,0.363509,0.685310,0.241733,0.336315,0.964126,0.114704,0.317830,0.038240,...,0.202712,0.493493,0.798936,0.133574,0.517971,1.227941,0.001384,0.491061,0.689320,0.438226
50%,15135.500000,151.35500,0.373814,0.865378,0.325280,0.347307,1.192465,0.217933,0.320812,0.039381,...,0.213270,0.504169,1.020698,0.155107,0.529516,1.452606,0.216855,0.501934,0.873961,0.517032
75%,22703.250000,227.03250,0.381552,0.926533,0.402999,0.359868,1.373046,0.281231,0.323795,0.042049,...,0.215312,0.512045,1.215907,0.224965,0.541017,1.662156,0.304864,0.512387,0.912990,0.587279
max,30271.000000,302.71000,0.438262,1.236531,0.799652,0.456491,1.709092,0.900128,0.360014,0.365036,...,0.506074,0.611271,1.566762,0.767302,0.691859,2.000067,1.013549,0.571997,1.237549,1.020864

### Getting the label for converting the data

In [13]:
Label_1= Label.columns.values
Markers_Label = []

Markers_Set_Name = 'Minh:'

#Need to check the number of marker used in the experiment
#
Marker_number = num_markers
for i in range(0,Marker_number):
    Temp = Label_1[2+3*i]
    Temp_1 = Temp.replace(Markers_Set_Name, "") #Need to remove the Marker set name
    Markers_Label.append(Temp_1)
Markers_Label

['L.ASIS',
 'L.Acromium',
 'L.Heel',
 'L.Midfoot.Lat',
 'L.Midfoot.Sup',
 'L.Shank.Front',
 'L.Shank.Rear',
 'L.Shank.Upper',
 'L.Thigh.Front',
 'L.Thigh.Rear',
 'L.Thigh.Upper',
 'L.Toe.Lat',
 'L.Toe.Med',
 'L.Toe.Tip',
 'R.ASIS',
 'R.Acromium',
 'R.Heel',
 'R.Midfoot.Lat',
 'R.Midfoot.Sup',
 'R.Shank.Front',
 'R.Shank.Rear',
 'R.Shank.Upper',
 'R.Thigh.Front',
 'R.Thigh.Rear',
 'R.Thigh.Upper',
 'R.Toe.Lat',
 'R.Toe.Med',
 'R.Toe.Tip',
 'Sternum',
 'Top.Head',
 'V.Sacral']

### Convert the data and save to .trc file

In [14]:
output_name = setting.iloc[2,1]
output_path = setting.iloc[1,1]
if os.path.exists(output_path + output_name + '.trc'):
    os.remove(output_path + output_name + '.trc')
Markers.to_csv(output_path + output_name + '.trc',  sep='\t', index=False, header = False)

In [15]:
New_label_Coor = '\t'
New_label_Mar = 'Frame#\tTime'
Num_frames = f'{num_frames}'
Num_markers = f'{num_markers}' 

for i in range(0,Marker_number):
    New_label_Coor = New_label_Coor + '\t' + 'X' + str(i+1) +'\t' + 'Y' + str(i+1) + '\t' + 'Z' + str(i+1)
for i in range(0,Marker_number-1):
    New_label_Mar = New_label_Mar + '\t' + Markers_Label[i] + '\t\t'
New_label_Mar = New_label_Mar + '\t' + Markers_Label[Marker_number-1] + '\n'

In [16]:
Contents = 'PathFileType\t4\t' + '(X,Y,Z)\t' + output_name + '.trc' + '\n' \
            + 'DataRate\tCameraRate\tNumFrames\tNumMarkers\tUnits\tOrigDataRate\tOrigDataStartFrame\tOrigNumFrames' + '\n' \
            + '100\t100\t' + Num_frames + '\t' + Num_markers + '\t' + 'm\t100\t1\t' + Num_frames + '\n'

In [17]:
with open(output_path + output_name + '.trc', "r+") as f:
    old = f.read() # read everything in the file
    f.seek(0) # rewind
    f.write(Contents + New_label_Mar + New_label_Coor + '\n\n' + old) #